### PR TITLE
Use JDK8.

### PR DESCRIPTION
**Pull request by bmcustodio**
I don't know if there's any strong reason not to, but I guess this would come in handy for a number of people like me who wish to target 8.

### CODE REVIEW

**Comment by goldmann** [comment]
Thanks for suggestion. I don't see any reason not to upgrade to JDK 8, but I need to check with the developers. It would be ideally to ship both versions, but unfortunately it's not so easy to maintain all the combinations...

**Comment by bmcustodio** [comment]
@goldmann That's great. If you want to ship both versions instead I can perhaps amend the PR and have, for instance, two separate directories containing Dockerfiles differing only by the base image. Let me know what your thoughts on this are.

**Comment by goldmann** [comment]
I need to think about how to solve some limitation of the Docker HUB, so we can have meaningful and easy to understand tags/versions, without rebuilding unnecessary stuff and without manual work.

**Comment by airborn** [comment]
Any news on this one?

**Comment by goldmann** [comment]
Not yet, no. I do not have any ETA.

**Comment by goldmann** [comment]
Closing, since we already use JDK 8.

**Pull request closed without merging**
