### PR TITLE
Add additional docker image for arm64

### PR DESCRIPTION
**Pull request by krisgerhard**

### CODE REVIEW

**Comment by amoscatelli** [comment]
any hope for this to be merged soon ?
admin required ?

**Comment by krisgerhard** [comment]
Admin required. In the meantime you can find some multi-arch images here: https://hub.docker.com/r/cybexer/wildfly/tags

**Comment by amoscatelli** [comment]
Hi @krisgerhard !
That's what I am currently doing.
I was trying to get attention from some admin since we need an official wildfly arm64 image, because next step is to also have Keycloak arm64 images (keycloak is based on wildfly).

**Comment by krisgerhard** [comment]
@jmesnil

**Comment by alessandro-tucci-visiontech** [comment]
I wonder what is preventing the admins from merging this pull request.
An **official** arm64 image for Wildfly would be of huge benefit for all of those who work with Docker-based technologies.

From what @krisgerhard did, I guess that the technical account for this repository is @jmesnil . @jmesnil , is there any additional work which should be done in order for this pull request to be accepted?

**Comment by jmesnil** [comment]
@alessandro-tucci-visiontech sorry, this issue flew under my radar. I've no objections to merge it and will do it right now.

**Pull request merged**
